### ISSUE TITLE
Add reaction interface on unknown search

### ISSUE THREAD

**Issue by Ph4i1ur3** [DenizenScript/DenizenMetaBot#1]
Since the new MetaBot can smartly search events, when it fails to make a direct match, but can still make an assumption, add a reaction to the message from the bot. If a user clicks the reaction, it would bring up the suggested meta either by editing the message reacted on, or by treating it as a new command (with fresh output)

Example:
user: c exploda
Meta: Cannot Find Searched Command
Unknown command. Did you mean explode?
user: *clicks reaction*
Meta: *explode meta*

**Comment by mcmonkey4eva** [comment]
Added today :D  ref https://github.com/DenizenScript/DenizenMetaBot/commit/352d2446e65728226c829897ace9af775402df1f
